//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOMDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttrDefine
    {
        public string TmpId { get; set; }
        public string AttrId { get; set; }
        public string AttrNm { get; set; }
        public string AttrTp { get; set; }
        public int LockFlag { get; set; }
        public Nullable<System.DateTime> CrtDate { get; set; }
        public string Crter { get; set; }
        public Nullable<System.DateTime> LstUpdtDate { get; set; }
        public string LstUpdter { get; set; }
    }
}
